# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  artio-nvim = {
    pname = "artio-nvim";
    version = "3c692427444c4e1e3bf35cadc44c6c74ffadd9e9";
    src = fetchgit {
      url = "https://codeberg.org/comfysage/artio.nvim";
      rev = "3c692427444c4e1e3bf35cadc44c6c74ffadd9e9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-wJtU6M9dRHm/qsrF3MEI7BNCM3TAkycMAcmNbg1KC10=";
    };
    as = "artio.nvim";
    date = "2026-02-10";
  };
  evergarden-nvim = {
    pname = "evergarden-nvim";
    version = "1949d2b7ed441f18e0e58cd23ac4dfdd91b332e9";
    src = fetchgit {
      url = "https://codeberg.org/evergarden/nvim";
      rev = "1949d2b7ed441f18e0e58cd23ac4dfdd91b332e9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-n40y4UTWjxZq6m1Gc8gN6S4fSbEYBCCe1JEsM9O8pdQ=";
    };
    as = "evergarden";
    date = "2026-02-11";
  };
  lylla-nvim = {
    pname = "lylla-nvim";
    version = "5daeae021b1beb4e7244102a66a8b0fcb5254ce8";
    src = fetchgit {
      url = "https://codeberg.org/comfysage/lylla.nvim";
      rev = "5daeae021b1beb4e7244102a66a8b0fcb5254ce8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-6eY7Lw4x+iGqrV6IGuk76VocDk9KifdZFpl+xlJFSkc=";
    };
    as = "lylla.nvim";
    date = "2026-02-16";
  };
  lynn-nvim = {
    pname = "lynn-nvim";
    version = "1721a5a524b49232a367a3c9215adfa4e99644c4";
    src = fetchgit {
      url = "https://codeberg.org/comfysage/lynn.nvim";
      rev = "1721a5a524b49232a367a3c9215adfa4e99644c4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tQ3vFI8iANLOnf97wF5H5uHnKWlarMTqNqexK06XRpQ=";
    };
    as = "lynn";
    start = "true";
    date = "2026-01-04";
  };
}
