# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  artio-nvim = {
    pname = "artio-nvim";
    version = "9e9c54ed8bae53fa6458299acbc9e0c1e5c27645";
    src = fetchgit {
      url = "https://codeberg.org/comfysage/artio.nvim";
      rev = "9e9c54ed8bae53fa6458299acbc9e0c1e5c27645";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-R1XFIDqALwRos8wAfKn9D5qV//ZAN1ccsVg1tC76umQ=";
    };
    as = "artio.nvim";
    date = "2026-02-01";
  };
  evergarden-nvim = {
    pname = "evergarden-nvim";
    version = "d809abf3c5a213bc27962ac6296196ef5126b528";
    src = fetchgit {
      url = "https://codeberg.org/evergarden/nvim";
      rev = "d809abf3c5a213bc27962ac6296196ef5126b528";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NyRgKd+Ey3ZDlbqq07Vp1ztbMWGCZdKLVrOiPoipKZE=";
    };
    as = "evergarden";
    date = "2026-01-30";
  };
  lylla-nvim = {
    pname = "lylla-nvim";
    version = "07d61e9e970bbe4196acfd43b214fc333396f840";
    src = fetchgit {
      url = "https://codeberg.org/comfysage/lylla.nvim";
      rev = "07d61e9e970bbe4196acfd43b214fc333396f840";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-yv2DHzrzoEF0F1Hvy49PK+rBjptQxnNcummRm4+2RzI=";
    };
    as = "lylla.nvim";
    date = "2026-01-29";
  };
  lynn-nvim = {
    pname = "lynn-nvim";
    version = "1721a5a524b49232a367a3c9215adfa4e99644c4";
    src = fetchgit {
      url = "https://codeberg.org/comfysage/lynn.nvim";
      rev = "1721a5a524b49232a367a3c9215adfa4e99644c4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tQ3vFI8iANLOnf97wF5H5uHnKWlarMTqNqexK06XRpQ=";
    };
    as = "lynn";
    start = "true";
    date = "2026-01-04";
  };
}
