# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  artio-nvim = {
    pname = "artio-nvim";
    version = "36773f37b6b05b50e91777fd32351c80d995b928";
    src = fetchgit {
      url = "https://codeberg.org/comfysage/artio.nvim";
      rev = "36773f37b6b05b50e91777fd32351c80d995b928";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-nc0A3Z1nXl4m7GjF04PFIhZ94aQ78jVhAzFovcV31f0=";
    };
    as = "artio.nvim";
    date = "2026-02-21";
  };
  evergarden-nvim = {
    pname = "evergarden-nvim";
    version = "eaf4645312299fe767c9fc43b0cbf52e3a6e9598";
    src = fetchgit {
      url = "https://codeberg.org/evergarden/nvim";
      rev = "eaf4645312299fe767c9fc43b0cbf52e3a6e9598";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-iDrNT98kPKuUpjoIwS8x2WMbf+pJAEs/nWSAZTQZM8Q=";
    };
    as = "evergarden";
    date = "2026-02-22";
  };
  lylla-nvim = {
    pname = "lylla-nvim";
    version = "5e933b297fb04162607fe7b6b1d172d10066c72c";
    src = fetchgit {
      url = "https://codeberg.org/comfysage/lylla.nvim";
      rev = "5e933b297fb04162607fe7b6b1d172d10066c72c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-7+KjVbCD9ZSIJ7b/jtiUTzhjkYOg+i9xxCX4qvMWviY=";
    };
    as = "lylla.nvim";
    date = "2026-02-16";
  };
  lynn-nvim = {
    pname = "lynn-nvim";
    version = "1721a5a524b49232a367a3c9215adfa4e99644c4";
    src = fetchgit {
      url = "https://codeberg.org/comfysage/lynn.nvim";
      rev = "1721a5a524b49232a367a3c9215adfa4e99644c4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tQ3vFI8iANLOnf97wF5H5uHnKWlarMTqNqexK06XRpQ=";
    };
    as = "lynn";
    start = "true";
    date = "2026-01-04";
  };
}
